### ISSUE TITLE
What are the limitations running xaml in coreWF 

### ISSUE THREAD

**Issue by pabloarthurrodger** [uipath-open/corewf#194]
As I read on your documentation,  XAML produced by the designer (Visual Studio) can be run in CoreWF (with some limitations).  I will like to know what are those limitations?

Thanks in Advance,

**Comment by dmetzgar** [comment]
Just writing to let you know I saw your comment. I'd have to look into it a bit to have a detailed guide. 

OTMH, the following are not supported:
- Dynamic update, but very few people used that
- Interop activity to run any WF3 activities
- WCF activities like send and receive

**Comment by pabloarthurrodger** [comment]
Mr. Metzgar:

Thanks for your response, I appreciate it.  Just to let you know I am
starting to code a InstanceStore for Azure Data Tables.  When I finish it,
I will send it to you, but I have to warn you my experience is nowhere near
your experience or anyone at microsoft. I will share with you when it works
for me, and maybe if it looks fairly good maybe you can put it at your
quality standard.

Again, I appreciate your response,

Pablo Arthur
Dominican Republic.

**Comment by pabloarthurrodger** [comment]
As I was commenting, I am trying to create an InstanceStore for Azure Table
Storage for my application.  Is there a way I can get the code of
SqlWorkflowInstanceStore
<https://docs.microsoft.com/en-us/dotnet/api/system.activities.durableinstancing.sqlworkflowinstancestore>
class?
When I try the Store the first command that I get is
"CreateWorkflowOwnerWithIdentity" And there is Zero documentation of what
this method is supposed to do?

If possible I will appreciate it,

Pablo Arthur
Dominican Republic

**Comment by dmetzgar** [comment]
Looking forward to seeing your implementation! It should be an interesting challenge.

Please find the source code of SqlWorkflowInstanceStore here: https://referencesource.microsoft.com/#System.Activities.DurableInstancing/System/Activities/DurableInstancing/SqlWorkflowInstanceStore.cs

Also have a look at the instance store documentation here: https://docs.microsoft.com/dotnet/framework/windows-workflow-foundation/instance-stores

**Comment by pabloarthurrodger** [comment]
Dustin:

I have been reading a lot!!!, They APM Asynchronous Pattern, that is a
delegate with beginInvoke and EndInvoke.  (instead of most modern async
await)  ( I would like to change this also in the project)

but I get lost, My knowledge of deep understanding of the code is not deep
enough, or I am very dumb.  If is possible for you, point me to documents
that let me understand the following line of code in the
JsonFileINstanceStore in the Method BeginTryCommand

return new TypedCompletedAsyncResult<bool>(LoadWorkflow(context,
(LoadWorkflowCommand)command), callback, state);

  The TypedCompletedAsyncResult I believe is a Generic Class, but when I
Open the constructor it has the T <bool> and the Callback and State.    My
question what happend to "LoadWorkflow(context,
(LoadWorkflowCommand)command)" parameter?

Thanks in Advance,

Pablo

**Comment by dmetzgar** [comment]
The code for TypedCompletedAsyncResult is in the JsonFileInstanceStore example. Rather than try to understand the older IAsyncResult pattern, I suggest using the Nito.AsyncEx library to convert to/from TPL (Task-based). Take a look at the [interop documentation](https://github.com/StephenCleary/AsyncEx/blob/master/doc/Home.md#interop).
